### ISSUE TITLE
naming clash with GNOME file manager

### ISSUE THREAD

**Issue by strypey** [aaronpk/Nautilus#1]
This looks like a great project! Just wanted to tip you off that there was already a free code project called Nautilus, the [file manager for the GNOME desktop](https://en.wikipedia.org/wiki/GNOME_Files). It's been officially renamed to Files, but a lot of people still know it as Nautilus (I didn't know it had been renamed until I checked just now). To avoid confusion, it might be worth considering a rename while your project is still new. Totally up you though. Keep up the good work!

EDIT: clarified Nautilus has been renamed to Files. Removed extra URL that appeared from  nowhere ;)

**Comment by aaronpk** [comment]
Given that they changed the name of theirs, and that these two projects are not even remotely in the same category (desktop file manager vs internet-based social media), I'm going to keep the name.

**Comment by strypey** [comment]
Fair enough :) Just though I ought to give you a heads up.
